filter visualisation to only show non-0 values
gin-fizz/pollistics pull request #94
Opened 2016-12-20 20:20 UTC by Haroenv

drawback: you can't see things that have no votes
- possible solution: show a list of 0-votes below

What's your opinion?

<small>also changed a small thing in the handling of the tooltip of the barchart</small>

2016-12-21 10:58 UTC, elsmr requested changes
Looks pretty weird when it's just an empty page. Maybe an error message and a link back to the vote page?

2016-12-21 11:00 UTC, Haroenv commented
@eliasmeire did you check the changes? When it's totally empty it showed some text (already earlier),  but this change will only filter out the options that have no votes. I did this because the pie diagram puts the text labels for it in the center. Maybe only filter for that one, if the text colour is readable an empty line for the bar chart would clear up the point of having things you don't see back

2016-12-21 18:14 UTC, Maliek approved these changes
🤙

2016-12-23 09:50 UTC, elsmr approved these changes

2016-12-23 09:56 UTC, merged